from __future__ import annotations

class Options:
    case_sensitive: bool
    def __init__(self) -> None: ...

class error(Exception): ...

class _Match:
    def group(self, __group: int | str = 0) -> str | None: ...
    def start(self, __group: int | str = 0) -> int: ...
    def end(self, __group: int | str = 0) -> int: ...

class _Regexp:
    def search(self, text: str, pos: int | None = None, endpos: int | None = None) -> _Match | None: ...
    def match(self, text: str, pos: int | None = None, endpos: int | None = None) -> _Match | None: ...

def compile(pattern: str, options: Options | None = None) -> _Regexp: ...
def search(pattern: str, text: str, options: Options | None = None) -> _Match | None: ...
def match(pattern: str, text: str, options: Options | None = None) -> _Match | None: ...
def fullmatch(pattern: str, text: str, options: Options | None = None) -> _Match | None: ...
def findall(pattern: str, text: str, options: Options | None = None) -> list[str]: ...
def sub(pattern: str, repl: str, text: str, count: int = 0, options: Options | None = None) -> str: ...
def escape(text: str) -> str: ...
def purge() -> None: ...
