from collections.abc import Callable, Hashable
from dataclasses import field as _dc_field

from uuid import UUID, uuid4

from .domain_event import DomainEvent
from .entity import Entity, EntityID, Field, field


class Aggregate[TId: Hashable](Entity[TId]):
    """Base class for DDD aggregate roots, generic over the raw ID type ``TId``.

    Adds domain event collection and business rule checking on top of Entity.

    ``__invariants__`` (inherited from ``Entity``) are checked automatically
    after every ``__init__``.  Use ``@command(invariants=[...])`` or
    ``@command(invariants='all')`` to re-check after mutations.

    ---

    ## Mutation guard

    Any ``Field[Entity]`` field accessed **outside** a ``@command`` returns a
    ``ReadOnlyView`` proxy.  Writing through it raises ``AttributeError``::

        class Engine(UuidEntity):
            speed: Field[Speed]

        class Car(UuidAggregate):
            engine: Field[Engine]

            @command
            def tune(self, speed: Speed) -> None:
                self.engine.speed = speed   # OK — inside @command, real entity

        car = Car(engine=Engine(speed=Speed(0)))
        car.engine.speed = Speed(100)       # AttributeError: Cannot set 'speed'
                                            # on a read-only view of Engine.
                                            # Mutations must go through the
                                            # aggregate root's @command methods.

    Note: plain ``list[Entity]`` fields are not yet wrapped in a read-only
    view, so only ``Field[Entity]`` descriptors carry this protection.
    """

    __events: list[DomainEvent] = _dc_field(default_factory=list, init=False, repr=False)  # pyright: ignore[reportUnknownVariableType,reportGeneralTypeIssues]

    def raise_event(self, event: DomainEvent) -> None:
        self.__events.append(event)

    def get_events(self) -> list[DomainEvent]:
        return list(self.__events)

    def clear_events(self) -> None:
        self.__events.clear()


# todo create a multi tenant aggregate(identifier is both id+tenant!)
class UuidAggregate(Aggregate[UUID]):
    """Aggregate with a UUID primary key, auto-generated by default."""

    id: Field[EntityID[UUID]] = field(default_factory=lambda: EntityID(uuid4()))


def authority[**P, R](method: Callable[P, R]) -> Callable[P, R]:
    """Mark a method as an authority check for a cross-aggregate invariant.

    The decorated aggregate is loaded first by the ``DomainService``; its
    return value gates whether the other aggregate(s) may proceed.

    Example::

        class Tenant(UuidAggregate):
            @authority
            def can_add_member(self) -> bool:
                return self.member_count.value < self.plan.max_members.value
    """
    setattr(method, "_is_authority_check", True)
    return method
