from collections.abc import Hashable
from dataclasses import field

from uuid import UUID, uuid4

from .domain_event import DomainEvent
from .entity import Entity, EntityID, Field, vo_field


class Aggregate[TId: Hashable](Entity[TId]):
    """Base class for DDD aggregate roots, generic over the raw ID type ``TId``.

    Adds domain event collection and business rule checking on top of Entity.

    ``__invariants__`` (inherited from ``Entity``) are checked automatically
    after every ``__init__``.  Use ``@command(invariants=[...])`` or
    ``@command(invariants='all')`` to re-check after mutations.

    ---

    ## Mutation guard

    Any ``Field[Entity]`` field accessed **outside** a ``@command`` returns a
    ``ReadOnlyView`` proxy.  Writing through it raises ``AttributeError``::

        class Engine(UuidEntity):
            speed: Field[Speed]

        class Car(UuidAggregate):
            engine: Field[Engine]

            @command
            def tune(self, speed: Speed) -> None:
                self.engine.speed = speed   # OK — inside @command, real entity

        car = Car(engine=Engine(speed=Speed(0)))
        car.engine.speed = Speed(100)       # AttributeError: Cannot set 'speed'
                                            # on a read-only view of Engine.
                                            # Mutations must go through the
                                            # aggregate root's @command methods.

    Note: plain ``list[Entity]`` fields are not yet wrapped in a read-only
    view, so only ``Field[Entity]`` descriptors carry this protection.
    """

    _events: list[DomainEvent] = field(  # pyright: ignore[reportUnknownVariableType]
        default_factory=list, init=False, repr=False
    )

    def get_events(self) -> list[DomainEvent]:
        return list(self._events)

    def clear_events(self) -> None:
        self._events.clear()


# todo create a multi tenant aggregate(identifier is both id+tenant!)
class UuidAggregate(Aggregate[UUID]):
    """Aggregate with a UUID primary key, auto-generated by default."""

    id: Field[EntityID[UUID]] = vo_field(default_factory=lambda: EntityID(uuid4()))
